Repository 2024-KDT-JNA/Pentoryall, pull requests merged in 2024-03, with the labels that each got.

#2 #1 기본 프로젝트 추가
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/pentoriall/pentoriall/PentoriallApplication.java
  src/main/resources/application-default.yml
  src/test/java/com/pentoriall/pentoriall/PentoriallApplicationTests.java
Labels: ⚙️Setting

#7 #6 PR, Issue Template 재설정
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/pull-request-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️Setting

#8 #5 프로젝트 네이밍 변경
  build.gradle
  settings.gradle
  src/main/java/com/pentoryall/PentoryallApplication.java
  src/test/java/com/pentoryall/PentoryallApplicationTests.java
Labels: 🔧Refactor

#19 #14 프로젝트 공통 설정 추가(config, exception)
  build.gradle
  src/main/java/com/pentoryall/common/exception/CustomException.java
  src/main/java/com/pentoryall/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pentoryall/config/MessageConfig.java
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/config/WebConfig.java
  src/main/resources/mappers/_DefaultMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/reset.css
  src/main/resources/static/images/common/logo_pentoryall.png
  src/main/resources/static/images/temp/author.png
  src/main/resources/static/images/temp/profile.png
  src/main/resources/static/images/temp/thumbnail.png
  src/main/resources/static/js/common.js
  src/main/resources/static/libs/swiper-11.0.7/swiper-bundle.min.css
  src/main/resources/static/libs/swiper-11.0.7/swiper-bundle.min.js
  src/main/resources/static/libs/toastui-editor/toastui-editor.min.css
  src/main/resources/static/libs/toastui-editor/toastui-editor.min.js
  src/main/resources/templates/error/errorPage.html
  src/main/resources/templates/views/index.html
Labels: ⚙️Setting

#24 10 포스트 패키지 추가
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
Labels: ⚙️Setting

#25 11 댓글 패키지 추가
  src/main/java/com/pentoryall/comment/controller/CommentController.java
  src/main/java/com/pentoryall/comment/mapper/CommentMapper.java
  src/main/java/com/pentoryall/comment/service/CommentService.java
  src/main/java/com/pentoryall/post/dto/PostDTO.java
Labels: ⚙️Setting

#26 #15 관리자 패키지 설계
  src/main/java/com/pentoryall/admin/Controller/commentReportController.java
  src/main/java/com/pentoryall/admin/Controller/genreManageController.java
  src/main/java/com/pentoryall/admin/Controller/modifyPostController.java
  src/main/java/com/pentoryall/admin/Controller/payManageController.java
  src/main/java/com/pentoryall/admin/Controller/postReportController.java
  src/main/java/com/pentoryall/admin/Controller/userManageController.java
  src/main/java/com/pentoryall/admin/DTO/genreManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/noticeManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/reportManage.java
  src/main/java/com/pentoryall/admin/DTO/userManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/userSettlementDTO.java
  src/main/java/com/pentoryall/admin/Service/commentReportService.java
  src/main/java/com/pentoryall/admin/Service/genreManageService.java
  src/main/java/com/pentoryall/admin/Service/modifyPostService.java
  src/main/java/com/pentoryall/admin/Service/payManageService.java
  src/main/java/com/pentoryall/admin/Service/postReportService.java
  src/main/java/com/pentoryall/admin/Service/userManageService.java
  src/main/resources/mappers/commentReportMapper.xml
  src/main/resources/mappers/genreManageMapper.xml
  src/main/resources/mappers/modifyPostMapper.xml
  src/main/resources/mappers/payManageMapper.xml
  src/main/resources/mappers/postReportMapper.xml
  src/main/resources/mappers/userManageMapper.xml
Labels: ⚙️Setting

#27 #20, #21 포인트 충전 및 거래 패키지 구조
  src/main/java/com/pentoryall/point/controller/OrderController.java
  src/main/java/com/pentoryall/point/controller/TransactionController.java
  src/main/java/com/pentoryall/point/dto/ImpOrderDTO.java
  src/main/java/com/pentoryall/point/dto/OrderDTO.java
  src/main/java/com/pentoryall/point/dto/TransactionDTO.java
  src/main/java/com/pentoryall/point/mapper/OrderMapper.java
  src/main/java/com/pentoryall/point/mapper/TransactionMapper.java
  src/main/java/com/pentoryall/point/service/OrderService.java
  src/main/java/com/pentoryall/point/service/TransactionService.java
Labels: ⚙️Setting

#29 #16 회원패키지 구조 설계
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/dto/UserDTO.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/UserService.java
Labels: ⚙️Setting

#33 #12, #18 멤버십/ 구독 기초설계
  src/main/java/com/pentoryall/membership/controller/MembershipController.java
  src/main/java/com/pentoryall/membership/dto/MembershipDTO.java
  src/main/java/com/pentoryall/membership/dto/MembershipJoinDTO.java
  src/main/java/com/pentoryall/membership/mapper/membershipMapper.xml
  src/main/java/com/pentoryall/membership/service/MembershipService.java
  src/main/java/com/pentoryall/subscribe/controller/SubscribeController.java
  src/main/java/com/pentoryall/subscribe/dto/SubscribeDTO.java
  src/main/java/com/pentoryall/subscribe/mapper/SubscriberMapper.xml
  src/main/java/com/pentoryall/subscribe/service/SubscriberService.java
Labels: 🔧Refactor

#36 #3, #4 Thymeleaf Layout 적용
  src/main/java/com/pentoryall/common/controller/MainController.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/css/common.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/static/css/story.css
  src/main/resources/static/css/sub.css
  src/main/resources/static/css/user.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/links.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/layout/default.html
  src/main/resources/templates/layout/story.html
  src/main/resources/templates/views/_sample.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/story/_sample.html
  src/main/resources/templates/views/story/home.html
Labels: ✨ Feature, ⚙️Setting, 🎨Style

#37 Merge static files
  src/main/resources/static/_views/_form.html
  src/main/resources/static/_views/_popup.html
  src/main/resources/static/_views/_table.html
  src/main/resources/static/_views/admin-genre.html
  src/main/resources/static/_views/admin-post-modify.html
  src/main/resources/static/_views/admin-report-comment.html
  src/main/resources/static/_views/admin-report-post.html
  src/main/resources/static/_views/admin-settlement.html
  src/main/resources/static/_views/admin-user.html
  src/main/resources/static/_views/main.html
  src/main/resources/static/_views/membership-close-alert.html
  src/main/resources/static/_views/membership-create.html
  src/main/resources/static/_views/membership-delete.html
  src/main/resources/static/_views/membership-info.html
  src/main/resources/static/_views/membership-modify.html
  src/main/resources/static/_views/membership-register-intro.html
  src/main/resources/static/_views/membership-register-list-nothing.html
  src/main/resources/static/_views/membership-register-list.html
  src/main/resources/static/_views/membership-register-popup.html
  src/main/resources/static/_views/mystory-subsciber-list-private.html
  src/main/resources/static/_views/mystory-subscriber-list.html
  src/main/resources/static/_views/point-recharge-list.html
  src/main/resources/static/_views/point-recharge-result.html
  src/main/resources/static/_views/point-recharge.html
  src/main/resources/static/_views/point-transaction-list.html
  src/main/resources/static/_views/point-transaction-membership.html
  src/main/resources/static/_views/point-transaction-post.html
  src/main/resources/static/_views/post-add.html
  src/main/resources/static/_views/post-page.html
  src/main/resources/static/_views/report-popup-comment.html
  src/main/resources/static/_views/report-popup-post.html
  src/main/resources/static/_views/revenue-list.html
  src/main/resources/static/_views/series-add.html
  src/main/resources/static/_views/series-page.html
  src/main/resources/static/_views/series-post-select.html
  src/main/resources/static/_views/settlement-request-list.html
  src/main/resources/static/_views/settlement-request-result.html
  src/main/resources/static/_views/settlement-request.html
  src/main/resources/static/_views/story.html
  src/main/resources/static/_views/subscribe-list-nothing.html
  src/main/resources/static/_views/subscribe-list.html
  src/main/resources/static/_views/subscribe-post-nothing.html
  src/main/resources/static/_views/subscribe-post.html
  src/main/resources/static/_views/user-certification.html
  src/main/resources/static/_views/user-login.html
  src/main/resources/static/_views/user-regist.html
  src/main/resources/static/_views/user-settlement-info.html
  src/main/resources/static/css/common.css
  src/main/resources/static/js/common.js
Labels: ⚙️Setting

#43 #40 포인트, 수익 패키지 재구성
  src/main/java/com/pentoryall/order/controller/OrderController.java
  src/main/java/com/pentoryall/order/dto/ImpOrderDTO.java
  src/main/java/com/pentoryall/order/dto/OrderDTO.java
  src/main/java/com/pentoryall/order/mapper/OrderMapper.java
  src/main/java/com/pentoryall/order/service/OrderService.java
  src/main/java/com/pentoryall/point/mapper/OrderMapper.java
  src/main/java/com/pentoryall/settlement/controller/SettlementController.java
  src/main/java/com/pentoryall/settlement/controller/UserSettlementController.java
  src/main/java/com/pentoryall/settlement/dto/SettlementDTO.java
  src/main/java/com/pentoryall/settlement/dto/UserSettlementDTO.java
  src/main/java/com/pentoryall/settlement/mapper/SettlementMapper.java
  src/main/java/com/pentoryall/settlement/mapper/UserSettlementMapper.java
  src/main/java/com/pentoryall/settlement/service/SettlementService.java
  src/main/java/com/pentoryall/settlement/service/UserSettlementService.java
  src/main/java/com/pentoryall/transaction/controller/TransactionController.java
  src/main/java/com/pentoryall/transaction/dto/TransactionDTO.java
  src/main/java/com/pentoryall/transaction/mapper/TransactionMapper.java
  src/main/java/com/pentoryall/transaction/service/TransactionService.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/mappers/SettlementMapper.xml
  src/main/resources/mappers/TransactionMapper.xml
  src/main/resources/mappers/UserSettlementMapper.xml
Labels: ⚙️Setting

#44 #39 주문 페이지 추가 및 기타 변경사항
  src/main/java/com/pentoryall/order/controller/OrderController.java
  src/main/resources/static/_views/_form.html
  src/main/resources/static/css/common.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/point.css
  src/main/resources/static/js/order.js
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/layout/default.html
  src/main/resources/templates/layout/story.html
  src/main/resources/templates/views/point/order.html
  src/main/resources/templates/views/point/orderResult.html
  src/main/resources/templates/views/point/orderResultList.html
Labels: ✨ Feature

#51 #46 회원기능개발
  build.gradle
  src/main/java/com/pentoryall/PentoryallApplication.java
  src/main/java/com/pentoryall/common/exception/user/LoginFailedException.java
  src/main/java/com/pentoryall/common/exception/user/MemberModifyException.java
  src/main/java/com/pentoryall/common/exception/user/MemberRegistException.java
  src/main/java/com/pentoryall/common/exception/user/MemberRemoveException.java
  src/main/java/com/pentoryall/config/MessageConfig.java
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/config/WebConfig.java
  src/main/java/com/pentoryall/email/service/EmailMessage.java
  src/main/java/com/pentoryall/email/service/EmailSendService.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/dto/UserDTO.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/model/Role.java
  src/main/java/com/pentoryall/user/service/AuthService.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/application-default.yml
  src/main/resources/mappers/UserMappers.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/_views/main.html
  src/main/resources/static/_views/story.html
  src/main/resources/static/_views/user-login.html
  src/main/resources/static/_views/user-regist.html
  src/main/resources/static/common/js/common.js
  src/main/resources/static/css/user.css
  src/main/resources/static/images/checkbox-active.svg
  src/main/resources/static/images/checkbox-inactive.svg
  src/main/resources/static/js/agree.js
  src/main/resources/static/js/event.js
  src/main/resources/static/js/user.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/main.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/regist.html
Labels: ✨ Feature

#54 Merge Chore/clean files
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layouts/main.html
Labels: ⚙️Setting

#55 #48 시리즈 추가
  src/main/java/com/pentoryall/post/controller/PostApiController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/dto/SeriesDTO.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/_views/series-page.html
  src/main/resources/static/css/post.css
  src/main/resources/static/images/temp/series-thumbnail.png
  src/main/resources/static/images/temp/자물쇠.png
  src/main/resources/templates/post/add.html
  src/main/resources/templates/series/add.html
  src/main/resources/templates/series/page.html
  src/main/resources/templates/views/index.html
  src/main/resources/upload/6c2aa4e334b940ba8af88b255138c07e.png
  src/main/resources/upload/af8318f2f53e432b935163af26a6c61c.png
  src/main/resources/upload/c0866439c74740e28a0d3c1291334c8b.png
Labels: ✨ Feature

#63 #46 템플릿 적용 및 회원정보관련 페이지 기능
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/email/service/EmailSendService.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/UserMappers.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/user.css
  src/main/resources/static/js/event.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/user/findPwd.html
  src/main/resources/templates/views/user/likePage.html
  src/main/resources/templates/views/user/login.html
  src/main/resources/templates/views/user/myModify.html
  src/main/resources/templates/views/user/notLikePage.html
  src/main/resources/templates/views/user/popUp.html
  src/main/resources/templates/views/user/regist.html
  src/main/resources/templates/views/user/withdrawal.html
Labels: ✨ Feature

#64 #39 포인트 충전 페이지 및 포트원 연동
  src/main/java/com/pentoryall/common/exception/CustomException.java
  src/main/java/com/pentoryall/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pentoryall/common/exception/order/OrderFailedException.java
  src/main/java/com/pentoryall/order/controller/OrderController.java
  src/main/java/com/pentoryall/order/dto/OrderDTO.java
  src/main/java/com/pentoryall/order/dto/PaymentDTO.java
  src/main/java/com/pentoryall/order/dto/PaymentRequestDTO.java
  src/main/java/com/pentoryall/order/dto/PaymentResponseDTO.java
  src/main/java/com/pentoryall/order/mapper/OrderMapper.java
  src/main/java/com/pentoryall/order/mapper/PaymentMapper.java
  src/main/java/com/pentoryall/order/service/OrderService.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/mappers/UserMappers.xml
  src/main/resources/static/css/point.css
  src/main/resources/static/js/order.js
  src/main/resources/templates/views/point/order.html
  src/main/resources/templates/views/point/orderResult.html
  src/main/resources/templates/views/point/orderResultList.html
  src/main/resources/templates/views/point/pointRechargeHistory.html
  src/test/java/com/pentoryall/order/mapper/OrderMapperTests.java
  src/test/java/com/pentoryall/order/mapper/PaymentMapperTests.java
Labels: ✨ Feature

#65 #59 멤버십 기능 수정
  src/main/java/com/pentoryall/membership/controller/MembershipController.java
  src/main/java/com/pentoryall/membership/dto/MembershipDTO.java
  src/main/java/com/pentoryall/membership/mapper/MembershipMapper.java
  src/main/java/com/pentoryall/membership/mapper/membershipMapper.xml
  src/main/java/com/pentoryall/membership/service/MembershipService.java
  src/main/resources/application-default.yml
  src/main/resources/mappers/MembershipMapper.xml
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/membership/createMembership.html
  src/main/resources/templates/views/membership/failCreate.html
  src/main/resources/templates/views/membership/successCreate.html
Labels: ✨ Feature

#66 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️Setting

#67 #56 시리즈 페이지, 포스트 페이지 동작 수정
  src/main/java/com/pentoryall/config/WebConfig.java
  src/main/java/com/pentoryall/post/controller/PostApiController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/dto/SeriesDTO.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/resources/application-default.yml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/static/css/post.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/post/add.html
  src/main/resources/templates/post/list.html
  src/main/resources/templates/post/tem.html
  src/main/resources/templates/post/writer.html
  src/main/resources/templates/series/add.html
  src/main/resources/templates/views/post/add.html
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/post/writer.html
  src/main/resources/templates/views/series/add.html
  src/main/resources/templates/views/series/page.html
Labels: 🔧Refactor

#69 #46 회원기능 관련 수정
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/user/controller/LikeController.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/UserMappers.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/_views/story.html
  src/main/resources/static/css/story.css
  src/main/resources/static/css/user.css
  src/main/resources/static/js/event.js
  src/main/resources/static/js/user.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/user/findPwd.html
  src/main/resources/templates/views/user/likePage.html
  src/main/resources/templates/views/user/login.html
  src/main/resources/templates/views/user/myModify.html
  src/main/resources/templates/views/user/regist.html
  src/main/resources/templates/views/user/withdrawal.html
Labels: ✨ Feature

#71 #46, #69 Merge 오류 수정
  src/main/java/com/pentoryall/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/resources/static/js/common.js
  src/main/resources/static/js/event.js
  src/main/resources/templates/views/user/regist.html
Labels: ⚙️Setting

#73 #72 멤버십 개설 및 조회 기능 완성
  src/main/java/com/pentoryall/membership/controller/MembershipController.java
  src/main/java/com/pentoryall/membership/dto/MembershipDTO.java
  src/main/java/com/pentoryall/membership/mapper/MembershipMapper.java
  src/main/java/com/pentoryall/membership/service/MembershipService.java
  src/main/resources/application-default.yml
  src/main/resources/mappers/MembershipMapper.xml
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/_sample.html
  src/main/resources/templates/views/membership/createMembership.html
  src/main/resources/templates/views/membership/failCreate.html
  src/main/resources/templates/views/membership/membership-register-intro.html
  src/main/resources/templates/views/membership/membership-register-list-nothing.html
  src/main/resources/templates/views/membership/membership-register-list.html
  src/main/resources/templates/views/membership/membership-register-popup.html
  src/main/resources/templates/views/membership/membershipInfo.html
  src/main/resources/templates/views/membership/membershipInfo2.html
  src/main/resources/templates/views/membership/membershipInfo3.html
  src/main/resources/templates/views/membership/planInfo.html
  src/main/resources/templates/views/membership/successCreate.html
Labels: ✨ Feature
