Repository 2024-KDT-JNA/Pentoryall, pull requests merged in 2024-04, with the labels that each got.

#76 #56 시리즈 페이즈에 해당하는 포스트들 나열
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/genre/controller/GenreController.java
  src/main/java/com/pentoryall/genre/dto/GenreDTO.java
  src/main/java/com/pentoryall/genre/mapper/GenreMapper.java
  src/main/java/com/pentoryall/genre/service/GenreService.java
  src/main/java/com/pentoryall/genreOfArt/controller/GenreOfArtController.java
  src/main/java/com/pentoryall/genreOfArt/dto/GenreOfArtDTO.java
  src/main/java/com/pentoryall/genreOfArt/mapper/GenreOfArtMapper.java
  src/main/java/com/pentoryall/genreOfArt/service/GenreOfArtService.java
  src/main/java/com/pentoryall/membership/controller/MembershipController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/resources/mappers/GenreMapper.xml
  src/main/resources/mappers/GenreOfArtMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/templates/views/post/add.html
  src/main/resources/templates/views/series/add.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
Labels: ✨ Feature, 🔧Refactor

#80 #39 포인트 충전 기능
  src/main/java/com/pentoryall/common/exception/order/InvalidOrderInfoException.java
  src/main/java/com/pentoryall/order/controller/OrderController.java
  src/main/java/com/pentoryall/order/dto/PaymentRequestDTO.java
  src/main/java/com/pentoryall/order/dto/PaymentResponseDTO.java
  src/main/java/com/pentoryall/order/mapper/OrderMapper.java
  src/main/java/com/pentoryall/order/mapper/PaymentMapper.java
  src/main/java/com/pentoryall/order/service/OrderService.java
  src/main/java/com/pentoryall/point/controller/PointOrderController.java
  src/main/java/com/pentoryall/point/controller/PointTransactionController.java
  src/main/java/com/pentoryall/point/dto/OrderDTO.java
  src/main/java/com/pentoryall/point/dto/OrderRequestDTO.java
  src/main/java/com/pentoryall/point/dto/OrderUserDTO.java
  src/main/java/com/pentoryall/point/dto/PaymentDTO.java
  src/main/java/com/pentoryall/point/dto/TransactionDTO.java
  src/main/java/com/pentoryall/point/mapper/OrderMapper.java
  src/main/java/com/pentoryall/point/mapper/PaymentMapper.java
  src/main/java/com/pentoryall/point/mapper/TransactionMapper.java
  src/main/java/com/pentoryall/point/service/OrderService.java
  src/main/java/com/pentoryall/point/service/TransactionService.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/mappers/TransactionMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/static/css/point.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/order.js
  src/main/resources/static/js/portone.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/point/order.html
  src/main/resources/templates/views/point/orderList.html
  src/main/resources/templates/views/point/orderResult.html
  src/main/resources/templates/views/point/paymentHistory.html
  src/test/java/com/pentoryall/order/mapper/OrderMapperTests.java
  src/test/java/com/pentoryall/order/mapper/PaymentMapperTests.java
  src/test/java/com/pentoryall/point/mapper/OrderMapperTests.java
  src/test/java/com/pentoryall/point/mapper/PaymentMapperTests.java
  src/test/java/com/pentoryall/user/mapper/UserMapperTests.java
Labels: ✨ Feature

#79 #78 시리즈에 해당하는 포스트 목록 출력
  src/main/java/com/pentoryall/email/service/EmailSendService.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/resources/application-yml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/images/temp/adult.png
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/post/add.html
  src/main/resources/templates/views/post/writer.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
  src/main/resources/upload/1c6bf7f4b9794181b387c13018c3bd8c.png
  src/main/resources/upload/2eacb42ec490452fb18085e94d7b3f66.png
  src/main/resources/upload/3af8cee33dd844d2a0cc56e0f72f9a7b.png
  src/main/resources/upload/584427d88f6d4b86ae63c5014ed1e16e.png
  src/main/resources/upload/61edc71befb440b6a333600c123bd20e.png
  src/main/resources/upload/6ceb32114fe54ad898983d92bd4e4ec8.png
Labels: ✨ Feature

#87 #86 포스트 삭제 기능 추가
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/views/series/page.html
Labels: ✨ Feature

#89 #88 시리즈 삭제 기능
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/mappers/UserMappers.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/templates/views/post/update.html
  src/main/resources/templates/views/series/add.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
Labels: ✨ Feature

#91 #90 메인 페이지에 이번 주 인기 시리즈 출력
  src/main/java/com/pentoryall/common/controller/MainController.java
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/main.css
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/post/update.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
Labels: ✨ Feature

#95 Merge/90, 91 fix
  src/main/java/com/pentoryall/genre/controller/GenreController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
Labels: ✨ Feature

#94 #70 좋아요, 이메일인증 기능 개발
  .gitignore
  src/main/java/com/pentoryall/email/controller/ApiEmailController.java
  src/main/java/com/pentoryall/email/service/EmailVerifyService.java
  src/main/java/com/pentoryall/user/controller/LikeController.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/mapper/LikeMapper.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/LikeService.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/application-yml
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/user.css
  src/main/resources/static/js/agree.js
  src/main/resources/static/js/event.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/email/auth.html
  src/main/resources/templates/views/user/myModify.html
  src/main/resources/templates/views/user/regist.html
  src/main/resources/templates/views/user/withdrawal.html
  src/main/resources/upload/0e83c57d581a4fc9ad292e7aecc50b9c.jpg
  src/main/resources/upload/1c6bf7f4b9794181b387c13018c3bd8c.png
  src/main/resources/upload/2eacb42ec490452fb18085e94d7b3f66.png
  src/main/resources/upload/3af8cee33dd844d2a0cc56e0f72f9a7b.png
  src/main/resources/upload/43ffeb4b10704ee9bb12a7f1bdfd5fc4.jpg
  src/main/resources/upload/561cfabb4f2d4bc9b3d6dc9efbc0401c.jpg
  src/main/resources/upload/584427d88f6d4b86ae63c5014ed1e16e.png
  src/main/resources/upload/61edc71befb440b6a333600c123bd20e.png
  src/main/resources/upload/6ceb32114fe54ad898983d92bd4e4ec8.png
  src/main/resources/upload/73c341fc8e99458985ad72595c96956d.png
  src/main/resources/upload/f3cf114099be442e8b17575d27cdc8ee.jpg
  src/main/resources/upload/f9c292500efc492c8e76276403c745ea.jpg
Labels: ✨ Feature

#97 #96 인기 포스트 화면에 출력
  .gitignore
  src/main/java/com/pentoryall/common/controller/MainController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/user/controller/LikeController.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/dto/LikeDTO.java
  src/main/java/com/pentoryall/user/dto/UserDTO.java
  src/main/java/com/pentoryall/user/mapper/LikeMapper.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/AuthService.java
  src/main/java/com/pentoryall/user/service/LikeService.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/main.css
  src/main/resources/static/js/event.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/_sample.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/post/add.html
  src/main/resources/templates/views/post/update.html
  src/main/resources/templates/views/series/add.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
  src/main/resources/templates/views/user/findPwd.html
  src/main/resources/templates/views/user/login.html
  src/main/resources/templates/views/user/myModify.html
  src/main/resources/templates/views/user/notLikePage.html
  src/main/resources/templates/views/user/popUp.html
  src/main/resources/templates/views/user/withdrawal.html
  src/main/resources/upload/0e83c57d581a4fc9ad292e7aecc50b9c.jpg
  src/main/resources/upload/1c6bf7f4b9794181b387c13018c3bd8c.png
  src/main/resources/upload/2eacb42ec490452fb18085e94d7b3f66.png
  src/main/resources/upload/3af8cee33dd844d2a0cc56e0f72f9a7b.png
  src/main/resources/upload/43ffeb4b10704ee9bb12a7f1bdfd5fc4.jpg
  src/main/resources/upload/561cfabb4f2d4bc9b3d6dc9efbc0401c.jpg
  src/main/resources/upload/584427d88f6d4b86ae63c5014ed1e16e.png
  src/main/resources/upload/61edc71befb440b6a333600c123bd20e.png
  src/main/resources/upload/6ceb32114fe54ad898983d92bd4e4ec8.png
  src/main/resources/upload/73c341fc8e99458985ad72595c96956d.png
  src/main/resources/upload/f3cf114099be442e8b17575d27cdc8ee.jpg
  src/main/resources/upload/f9c292500efc492c8e76276403c745ea.jpg
Labels: ✨ Feature

#99 #98 제목,작가,제목+작가 검색에 따른 결과 출력
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/main.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/select.html
Labels: ✨ Feature

#100 #72 멤버십 개설 조회 삭제
  src/main/java/com/pentoryall/membership/controller/MembershipController.java
  src/main/java/com/pentoryall/membership/dto/MembershipDTO.java
  src/main/java/com/pentoryall/membership/mapper/MembershipMapper.java
  src/main/java/com/pentoryall/membership/service/MembershipService.java
  src/main/java/com/pentoryall/subscribe/mapper/SubscriberMapper.xml
  src/main/java/com/pentoryall/user/dto/UserDTO.java
  src/main/resources/mappers/MembershipMapper.xml
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/membership/deleteMembership.html
  src/main/resources/templates/views/membership/errorPage.html
  src/main/resources/templates/views/membership/failDelete.html
  src/main/resources/templates/views/membership/failModify.html
  src/main/resources/templates/views/membership/membershipModify.html
  src/main/resources/templates/views/membership/planInfo.html
  src/main/resources/templates/views/membership/successDelete.html
  src/main/resources/templates/views/membership/successModify.html
Labels: ✨ Feature

#102 #81 정산 정보 조회 및 공통 레이아웃
  src/main/java/com/pentoryall/settlement/controller/UserSettlementController.java
  src/main/java/com/pentoryall/settlement/dto/SettlementDTO.java
  src/main/java/com/pentoryall/settlement/dto/UserSettlementDTO.java
  src/main/java/com/pentoryall/settlement/mapper/UserSettlementMapper.java
  src/main/java/com/pentoryall/settlement/service/UserSettlementService.java
  src/main/java/com/pentoryall/settlement/status/SettlementState.java
  src/main/resources/mappers/UserSettlementMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/static/css/sub.css
  src/main/resources/templates/fragments/settings/sidebar.html
  src/main/resources/templates/layout/settings.html
  src/main/resources/templates/views/user/settlement/add.html
Labels: ✨ Feature

#106 #105 장르관리 구현과 신고관리 그리고 수정관리의 조회
  build.gradle
  src/main/java/com/pentoryall/admin/Controller/CommentReportController.java
  src/main/java/com/pentoryall/admin/Controller/GenreManageController.java
  src/main/java/com/pentoryall/admin/Controller/ModifyPostController.java
  src/main/java/com/pentoryall/admin/Controller/PostReportController.java
  src/main/java/com/pentoryall/admin/Controller/modifyPostController.java
  src/main/java/com/pentoryall/admin/DTO/GenreManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/PostReportDTO.java
  src/main/java/com/pentoryall/admin/DTO/ReportManageDTO.java
  src/main/java/com/pentoryall/admin/Service/CommentReportService.java
  src/main/java/com/pentoryall/admin/Service/GenreManageService.java
  src/main/java/com/pentoryall/admin/Service/ModifyPostService.java
  src/main/java/com/pentoryall/admin/Service/PostReportService.java
  src/main/java/com/pentoryall/admin/Service/modifyPostService.java
  src/main/java/com/pentoryall/admin/mapper/CommentReportMapper.java
  src/main/java/com/pentoryall/admin/mapper/GenreManageMapper.java
  src/main/java/com/pentoryall/admin/mapper/ModifyPostMapper.java
  src/main/java/com/pentoryall/admin/mapper/PostReportMapper.java
  src/main/java/com/pentoryall/admin/mapper/UserManageMapper.java
  src/main/java/com/pentoryall/post/dto/PostDTO.java
  src/main/resources/application-yml
  src/main/resources/mappers/GenreManageMapper.xml
  src/main/resources/mappers/ModifyPostMapper.xml
  src/main/resources/mappers/PostReportMapper.xml
  src/main/resources/static/css/admin.css
  src/main/resources/templates/views/admin/adminCommentReport.html
  src/main/resources/templates/views/admin/adminGenre.html
  src/main/resources/templates/views/admin/adminPostModify.html
  src/main/resources/templates/views/admin/adminPostReport.html
  src/main/resources/templates/views/admin/adminSettlement.html
Labels: ✨ Feature

#107 #104 정산 정보 등록, 수정
  build.gradle
  src/main/java/com/pentoryall/admin/DTO/userSettlementDTO.java
  src/main/java/com/pentoryall/common/controller/PortOneApiController.java
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/settlement/controller/UserSettlementController.java
  src/main/java/com/pentoryall/settlement/dto/UserSettlementDTO.java
  src/main/java/com/pentoryall/settlement/mapper/UserSettlementMapper.java
  src/main/java/com/pentoryall/settlement/service/UserSettlementService.java
  src/main/resources/application-yml
  src/main/resources/mappers/UserSettlementMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/sub.css
  src/main/resources/static/js/settlement.js
  src/main/resources/templates/fragments/common/messageAlert.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/links.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/layout/settings.html
  src/main/resources/templates/views/user/settlement/add.html
Labels: ✨ Feature, ⚙️Setting, 🔧Refactor

#108 #70 로그인, 좋아요 기능개발 수정
  profile-images/a5a027df-57f0-4455-94ed-ac44208ff19e.jpeg
  src/main/java/com/pentoryall/config/EmailConfig.java
  src/main/java/com/pentoryall/email/controller/ApiEmailController.java
  src/main/java/com/pentoryall/email/service/EmailMessage.java
  src/main/java/com/pentoryall/email/service/EmailSendService.java
  src/main/java/com/pentoryall/email/service/EmailVerifyService.java
  src/main/java/com/pentoryall/email/service/MailService.java
  src/main/java/com/pentoryall/user/controller/LikeController.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/dto/LikeDTO.java
  src/main/java/com/pentoryall/user/dto/LikePostDTO.java
  src/main/java/com/pentoryall/user/mapper/LikeMapper.java
  src/main/java/com/pentoryall/user/mapper/LikePostMapper.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/LikePostService.java
  src/main/java/com/pentoryall/user/service/LikeService.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/mappers/LikePostMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/messages/messages_ko_KR.properties
  src/main/resources/static/css/user.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/event.js
  src/main/resources/static/js/like.js
  src/main/resources/static/js/user.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/_sample.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/user/findPwd.html
  src/main/resources/templates/views/user/like.html
  src/main/resources/templates/views/user/likePage.html
  src/main/resources/templates/views/user/myModify.html
  src/main/resources/templates/views/user/regist.html
  src/main/resources/templates/views/user/withdrawal.html
Labels: ✨ Feature

#109 #103 구독 좋아요 기능 / 페이지 매핑
  src/main/java/com/pentoryall/membership/dto/MembershipJoinDTO.java
  src/main/java/com/pentoryall/settlement/controller/UserSettlementController.java
  src/main/java/com/pentoryall/settlement/mapper/UserSettlementMapper.java
  src/main/java/com/pentoryall/settlement/service/UserSettlementService.java
  src/main/java/com/pentoryall/subscribe/controller/SubscribeController.java
  src/main/java/com/pentoryall/subscribe/dto/SubscribeDTO.java
  src/main/java/com/pentoryall/subscribe/mapper/SubscribeMapper.java
  src/main/java/com/pentoryall/subscribe/service/SubscribeService.java
  src/main/java/com/pentoryall/subscribe/service/SubscriberService.java
  src/main/java/com/pentoryall/user/dto/UserDTO.java
  src/main/resources/mappers/MembershipMapper.xml
  src/main/resources/mappers/SubscribeMapper.xml
  src/main/resources/mappers/UserSettlementMapper.xml
  src/main/resources/static/css/sub.css
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/layout/settings.html
  src/main/resources/templates/views/membership/deleteMembership.html
  src/main/resources/templates/views/membership/membershipInfo2.html
  src/main/resources/templates/views/membership/membershipInfo3.html
  src/main/resources/templates/views/subscribe/noStoryList.html
  src/main/resources/templates/views/subscribe/noSubscriberList.html
  src/main/resources/templates/views/subscribe/storyList.html
  src/main/resources/templates/views/subscribe/subscribe-list-nothing.html
  src/main/resources/templates/views/subscribe/subscribe-list.html
  src/main/resources/templates/views/subscribe/subscriberList.html
  src/main/resources/templates/views/user/settlement/add.html
Labels: ✨ Feature

#114 #104 정산 정보 등록 시 계좌 검증
  src/main/java/com/pentoryall/portone/controller/PortOneApiController.java
  src/main/java/com/pentoryall/portone/service/PortOneService.java
  src/main/java/com/pentoryall/settlement/dto/UserSettlementDTO.java
  src/main/resources/mappers/UserSettlementMapper.xml
  src/main/resources/static/js/settlement.js
  src/main/resources/templates/views/user/settlement/add.html
Labels: ✨ Feature

#116 #111 댓글 수정 기능 추가
  src/main/java/com/pentoryall/comment/dto/CommentDetailDTO.java
  src/main/java/com/pentoryall/comment/mapper/CommentMapper.java
  src/main/java/com/pentoryall/comment/service/CommentService.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/resources/mappers/CommentMapper.xml
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/post/writer.html
Labels: ✨ Feature

#124 #70 회원, 좋아요 기능 개발
  src/main/java/com/pentoryall/common/exception/user/EmailCodeException.java
  src/main/java/com/pentoryall/config/EmailConfig.java
  src/main/java/com/pentoryall/email/EmailProperties.java
  src/main/java/com/pentoryall/email/MailServiceInter.java
  src/main/java/com/pentoryall/email/RedisUtil.java
  src/main/java/com/pentoryall/email/controller/AccountController.java
  src/main/java/com/pentoryall/email/service/FindPwMail.java
  src/main/java/com/pentoryall/email/service/MailService.java
  src/main/java/com/pentoryall/email/service/RegisterMail.java
  src/main/resources/application-yml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/static/css/user.css
  src/main/resources/static/js/email.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/user/likePage.html
  src/main/resources/templates/views/user/popUp.html
  src/main/resources/templates/views/user/regist.html
Labels: ✨ Feature

#129 Setting/#128 관리자 사이드바를 적용하고 오류를 해결하고 페이징처리를 수정하고 이것저것했습니다
  src/main/java/com/pentoryall/admin/Controller/GenreManageController.java
  src/main/java/com/pentoryall/admin/Controller/UserManageController.java
  src/main/java/com/pentoryall/admin/Service/GenreManageService.java
  src/main/java/com/pentoryall/admin/mapper/GenreManageMapper.java
  src/main/java/com/pentoryall/email/controller/AccountController.java
  src/main/java/com/pentoryall/email/service/MailService.java
  src/main/java/com/pentoryall/portone/controller/PortOneApiController.java
  src/main/java/com/pentoryall/portone/service/PortOneService.java
  src/main/resources/mappers/GenreManageMapper.xml
  src/main/resources/mappers/PostReportMapper.xml
  src/main/resources/mappers/UserManageMapper.xml
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/admin/adminCommentReport.html
  src/main/resources/templates/views/admin/adminGenre.html
  src/main/resources/templates/views/admin/adminPostModify.html
  src/main/resources/templates/views/admin/adminPostReport.html
  src/main/resources/templates/views/admin/adminSettlement.html
  src/main/resources/templates/views/admin/adminUser.html
Labels: ⚙️Setting

#131 #130 gitignore 변경 및 이미지 삭제
  .gitignore
  src/main/resources/upload/0e83c57d581a4fc9ad292e7aecc50b9c.jpg
  src/main/resources/upload/1c6bf7f4b9794181b387c13018c3bd8c.png
  src/main/resources/upload/2eacb42ec490452fb18085e94d7b3f66.png
  src/main/resources/upload/3af8cee33dd844d2a0cc56e0f72f9a7b.png
  src/main/resources/upload/43ffeb4b10704ee9bb12a7f1bdfd5fc4.jpg
  src/main/resources/upload/561cfabb4f2d4bc9b3d6dc9efbc0401c.jpg
  src/main/resources/upload/584427d88f6d4b86ae63c5014ed1e16e.png
  src/main/resources/upload/61edc71befb440b6a333600c123bd20e.png
  src/main/resources/upload/6ceb32114fe54ad898983d92bd4e4ec8.png
  src/main/resources/upload/73c341fc8e99458985ad72595c96956d.png
  src/main/resources/upload/f3cf114099be442e8b17575d27cdc8ee.jpg
  src/main/resources/upload/f9c292500efc492c8e76276403c745ea.jpg
Labels: ⚙️Setting

#133 #132 페이지 처리를 위한 Pagination을 fragment로 분리
  profile-images/a5a027df-57f0-4455-94ed-ac44208ff19e.jpeg
  src/main/java/com/pentoryall/admin/Controller/CommentReportController.java
  src/main/java/com/pentoryall/admin/Controller/GenreManageController.java
  src/main/java/com/pentoryall/admin/Controller/ModifyPostController.java
  src/main/java/com/pentoryall/admin/Controller/PostReportController.java
  src/main/java/com/pentoryall/admin/Controller/UserManageController.java
  src/main/java/com/pentoryall/admin/Controller/payManageController.java
  src/main/java/com/pentoryall/admin/DTO/CommentReportDTO.java
  src/main/java/com/pentoryall/admin/DTO/GenreManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/PostReportDTO.java
  src/main/java/com/pentoryall/admin/DTO/ReportManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/UserManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/noticeManageDTO.java
  src/main/java/com/pentoryall/admin/DTO/userSettlementDTO.java
  src/main/java/com/pentoryall/admin/Exception/MemberStopException.java
  src/main/java/com/pentoryall/admin/Service/CommentReportService.java
  src/main/java/com/pentoryall/admin/Service/GenreManageService.java
  src/main/java/com/pentoryall/admin/Service/ModifyPostService.java
  src/main/java/com/pentoryall/admin/Service/PostReportService.java
  src/main/java/com/pentoryall/admin/Service/UserManageService.java
  src/main/java/com/pentoryall/admin/Service/payManageService.java
  src/main/java/com/pentoryall/admin/mapper/CommentReportMapper.java
  src/main/java/com/pentoryall/admin/mapper/GenreManageMapper.java
  src/main/java/com/pentoryall/admin/mapper/ModifyPostMapper.java
  src/main/java/com/pentoryall/admin/mapper/PostReportMapper.java
  src/main/java/com/pentoryall/admin/mapper/UserManageMapper.java
  src/main/java/com/pentoryall/common/page/Pagination.java
  src/main/java/com/pentoryall/common/page/SelectCriteria.java
  src/main/java/com/pentoryall/portone/controller/PortOneApiController.java
  src/main/java/com/pentoryall/portone/service/PortOneService.java
  src/main/resources/mappers/CommentReportMapper.xml
  src/main/resources/mappers/GenreManageMapper.xml
  src/main/resources/mappers/PostReportMapper.xml
  src/main/resources/mappers/UserManageMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/fragments/common/pagination.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/admin/adminUser.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/series/update.html
Labels: ✨ Feature, 🔧Refactor

#135 Feature/134 구독 공개여부 기능
  src/main/java/com/pentoryall/subscribe/mapper/SubscriberMapper.xml
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/SubscribeMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/templates/views/user/myModify.html
Labels: ✨ Feature

#137 #70 로그인, 회원가입 기능 개발
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/email/controller/AccountController.java
  src/main/java/com/pentoryall/email/service/FindPwMail.java
  src/main/java/com/pentoryall/email/service/MailService.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/dto/UserDTO.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/css/user.css
  src/main/resources/static/js/email.js
  src/main/resources/static/js/like.js
  src/main/resources/static/js/user.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/user/findPwd.html
  src/main/resources/templates/views/user/likePage.html
  src/main/resources/templates/views/user/login.html
  src/main/resources/templates/views/user/myModify.html
  src/main/resources/templates/views/user/regist.html
Labels: ✨ Feature

#138 #136 포인트 충전 내역 조회
  src/main/java/com/pentoryall/common/dto/PageResponse.java
  src/main/java/com/pentoryall/common/page/Pagination.java
  src/main/java/com/pentoryall/config/SecurityConfig.java
  src/main/java/com/pentoryall/point/controller/PointOrderController.java
  src/main/java/com/pentoryall/point/dto/OrderDTO.java
  src/main/java/com/pentoryall/point/mapper/OrderMapper.java
  src/main/java/com/pentoryall/point/service/OrderService.java
  src/main/resources/mappers/OrderMapper.xml
  src/main/resources/static/_views/_form.html
  src/main/resources/static/_views/_popup.html
  src/main/resources/static/_views/_table.html
  src/main/resources/static/_views/main.html
  src/main/resources/static/_views/membership-close-alert.html
  src/main/resources/static/_views/membership-create.html
  src/main/resources/static/_views/membership-delete.html
  src/main/resources/static/_views/membership-info.html
  src/main/resources/static/_views/membership-modify.html
  src/main/resources/static/_views/membership-register-intro.html
  src/main/resources/static/_views/membership-register-list-nothing.html
  src/main/resources/static/_views/membership-register-list.html
  src/main/resources/static/_views/membership-register-popup.html
  src/main/resources/static/_views/mystory-subsciber-list-private.html
  src/main/resources/static/_views/mystory-subscriber-list.html
  src/main/resources/static/_views/point-recharge-list.html
  src/main/resources/static/_views/point-recharge-result.html
  src/main/resources/static/_views/point-recharge.html
  src/main/resources/static/_views/point-transaction-list.html
  src/main/resources/static/_views/point-transaction-membership.html
  src/main/resources/static/_views/point-transaction-post.html
  src/main/resources/static/_views/post-add.html
  src/main/resources/static/_views/post-page.html
  src/main/resources/static/_views/report-popup-comment.html
  src/main/resources/static/_views/report-popup-post.html
  src/main/resources/static/_views/revenue-list.html
  src/main/resources/static/_views/series-add.html
  src/main/resources/static/_views/series-page.html
  src/main/resources/static/_views/series-post-select.html
  src/main/resources/static/_views/settlement-request-list.html
  src/main/resources/static/_views/settlement-request-result.html
  src/main/resources/static/_views/settlement-request.html
  src/main/resources/static/_views/story.html
  src/main/resources/static/_views/subscribe-list-nothing.html
  src/main/resources/static/_views/subscribe-list.html
  src/main/resources/static/_views/subscribe-post-nothing.html
  src/main/resources/static/_views/subscribe-post.html
  src/main/resources/static/_views/user-certification.html
  src/main/resources/static/_views/user-login.html
  src/main/resources/static/_views/user-regist.html
  src/main/resources/static/_views/user-settlement-info.html
  src/main/resources/static/css/common.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/point/orderList.html
Labels: ✨ Feature

#139 #117 답글 조회,추가,삭제 기능 / 좋아요 온오프 기능,좋아요한 목록 조회 구현
  src/main/java/com/pentoryall/comment/mapper/CommentMapper.java
  src/main/java/com/pentoryall/comment/service/CommentService.java
  src/main/java/com/pentoryall/common/controller/MainController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/user/mapper/LikeMapper.java
  src/main/java/com/pentoryall/user/mapper/LikePostMapper.java
  src/main/java/com/pentoryall/user/service/LikePostService.java
  src/main/java/com/pentoryall/user/service/LikeService.java
  src/main/resources/mappers/CommentMapper.xml
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/mappers/LikePostMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/series/page.html
Labels: ✨ Feature

#144 #140 좋아요 시리즈 포스트 페이지에서 출력
  src/main/java/com/pentoryall/common/controller/MainController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/java/com/pentoryall/user/mapper/LikeMapper.java
  src/main/java/com/pentoryall/user/mapper/LikePostMapper.java
  src/main/java/com/pentoryall/user/service/LikePostService.java
  src/main/java/com/pentoryall/user/service/LikeService.java
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/mappers/LikePostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/series/page.html
Labels: ✨ Feature

#146 #145 조회수 기능 구현
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/java/com/pentoryall/user/controller/LikeController.java
  src/main/java/com/pentoryall/user/mapper/LikeMapper.java
  src/main/java/com/pentoryall/user/mapper/LikePostMapper.java
  src/main/java/com/pentoryall/user/service/LikePostService.java
  src/main/java/com/pentoryall/user/service/LikeService.java
  src/main/resources/mappers/LikeMapper.xml
  src/main/resources/mappers/LikePostMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/user/likePage.html
Labels: ✨ Feature

#150 #147 마이스토리 로그인한 회원이 만든 포스트,시리즈 확인
  src/main/java/com/pentoryall/genre/controller/GenreController.java
  src/main/java/com/pentoryall/genreOfArt/mapper/GenreOfArtMapper.java
  src/main/java/com/pentoryall/genreOfArt/service/GenreOfArtService.java
  src/main/java/com/pentoryall/story/controller/StoryController.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/story/home.html
  src/main/resources/templates/views/story/posts.html
  src/main/resources/templates/views/story/series.html
Labels: ✨ Feature

#152 #151 제목,작가,제목+작가로 검색되지 않던 오류를 해결
  src/main/resources/templates/fragments/header.html
Labels: 🐞Bug, 🔧Refactor

#154 #153 post 테이블의 price,views 자료형 int로 변환
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/dto/PostDTO.java
Labels: 🔧Refactor

#157 #155 포스트 수정 관리 및 css
  src/main/java/com/pentoryall/admin/Exception/MemberStopException.java
  src/main/java/com/pentoryall/admin/controller/CommentReportController.java
  src/main/java/com/pentoryall/admin/controller/GenreManageController.java
  src/main/java/com/pentoryall/admin/controller/ModifyPostController.java
  src/main/java/com/pentoryall/admin/controller/PostReportController.java
  src/main/java/com/pentoryall/admin/controller/UserManageController.java
  src/main/java/com/pentoryall/admin/controller/payManageController.java
  src/main/java/com/pentoryall/admin/dtos/CommentReportDTO.java
  src/main/java/com/pentoryall/admin/dtos/GenreManageDTO.java
  src/main/java/com/pentoryall/admin/dtos/ModifyPostDTO.java
  src/main/java/com/pentoryall/admin/dtos/PostReportDTO.java
  src/main/java/com/pentoryall/admin/dtos/ReportManageDTO.java
  src/main/java/com/pentoryall/admin/dtos/UserManageDTO.java
  src/main/java/com/pentoryall/admin/dtos/noticeManageDTO.java
  src/main/java/com/pentoryall/admin/dtos/userSettlementDTO.java
  src/main/java/com/pentoryall/admin/mappers/CommentReportMapper.java
  src/main/java/com/pentoryall/admin/mappers/GenreManageMapper.java
  src/main/java/com/pentoryall/admin/mappers/ModifyPostMapper.java
  src/main/java/com/pentoryall/admin/mappers/PayManageMapper.java
  src/main/java/com/pentoryall/admin/mappers/PostReportMapper.java
  src/main/java/com/pentoryall/admin/mappers/UserManageMapper.java
  src/main/java/com/pentoryall/admin/service/CommentReportService.java
  src/main/java/com/pentoryall/admin/service/GenreManageService.java
  src/main/java/com/pentoryall/admin/service/ModifyPostService.java
  src/main/java/com/pentoryall/admin/service/PostReportService.java
  src/main/java/com/pentoryall/admin/service/UserManageService.java
  src/main/java/com/pentoryall/admin/service/payManageService.java
  src/main/java/com/pentoryall/email/service/MailService.java
  src/main/java/com/pentoryall/membership/service/MembershipService.java
  src/main/java/com/pentoryall/portone/controller/PortOneApiController.java
  src/main/java/com/pentoryall/portone/service/PortOneService.java
  src/main/resources/mappers/CommentReportMapper.xml
  src/main/resources/mappers/GenreManageMapper.xml
  src/main/resources/mappers/ModifyPostMapper.xml
  src/main/resources/mappers/PayManageMapper.xml
  src/main/resources/mappers/PostReportMapper.xml
  src/main/resources/mappers/UserManageMapper.xml
  src/main/resources/static/css/admin.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/settings/sidebar.html
  src/main/resources/templates/views/admin/adminCommentReport.html
  src/main/resources/templates/views/admin/adminGenre.html
  src/main/resources/templates/views/admin/adminPostModify.html
  src/main/resources/templates/views/admin/adminPostReport.html
  src/main/resources/templates/views/admin/adminUser.html
Labels: ✨ Feature

#159 #158 스토리 경로 변경
  src/main/java/com/pentoryall/story/controller/StoryController.java
  src/main/resources/templates/fragments/story/header.html
  src/main/resources/templates/views/story/home.html
  src/main/resources/templates/views/story/posts.html
  src/main/resources/templates/views/story/series.html
Labels: 🐞Bug

#161 #82 유료 포스트 거래
  src/main/java/com/pentoryall/membership/mapper/MembershipMapper.java
  src/main/java/com/pentoryall/membership/service/MembershipService.java
  src/main/java/com/pentoryall/point/controller/PointTransactionApiController.java
  src/main/java/com/pentoryall/point/controller/PointTransactionController.java
  src/main/java/com/pentoryall/point/dto/TransactionDTO.java
  src/main/java/com/pentoryall/point/mapper/TransactionMapper.java
  src/main/java/com/pentoryall/point/service/TransactionService.java
  src/main/java/com/pentoryall/post/controller/PostApiController.java
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/dto/ValidatePostDTO.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/resources/mappers/MembershipMapper.xml
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/TransactionMapper.xml
  src/main/resources/static/js/post.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/membership/register.html
  src/main/resources/templates/views/series/page.html
Labels: ✨ Feature

#162 #83 수익 및 정산 관련 페이지 추가
  src/main/java/com/pentoryall/settlement/controller/SettlementController.java
  src/main/resources/static/css/point.css
  src/main/resources/templates/fragments/post/purchasePopup.html
  src/main/resources/templates/views/membership/register.html
  src/main/resources/templates/views/point/order.html
  src/main/resources/templates/views/point/orderList.html
  src/main/resources/templates/views/point/orderResult.html
  src/main/resources/templates/views/settlement/revenueList.html
  src/main/resources/templates/views/settlement/settlement.html
  src/main/resources/templates/views/settlement/settlementList.html
  src/main/resources/templates/views/settlement/settlementResult.html
Labels: ✨ Feature

#164 스토리 홈 오류 수정 및 탭 처리
  src/main/java/com/pentoryall/point/controller/PointTransactionApiController.java
  src/main/java/com/pentoryall/story/controller/StoryController.java
  src/main/resources/templates/fragments/story/header.html
Labels: 🐞Bug, 🎨Style

#166 #165 메인 및 검색 페이지 디자인과 에러 수정
  src/main/resources/static/css/common.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/static/css/sub.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/_sample.html
  src/main/resources/templates/views/admin/adminGenre.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/post/add.html
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/post/update.html
  src/main/resources/templates/views/post/updatewriter.html
  src/main/resources/templates/views/post/writer.html
  src/main/resources/templates/views/series/add.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/select.html
  src/main/resources/templates/views/story/_sample.html
  src/main/resources/templates/views/user/login.html
Labels: 🐞Bug, 🎨Style

#167 #156 DELETE로 삭제 했던 포스트, 시리즈 UPDATE is_delete를 통해 삭제 처리
  src/main/java/com/pentoryall/common/exception/GlobalExceptionHandler.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/java/com/pentoryall/series/mapper/SeriesMapper.java
  src/main/java/com/pentoryall/series/service/SeriesService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/series/update.html
  src/main/resources/templates/views/story/home.html
Labels: 🐞Bug, 🔧Refactor

#171 포스트, 시리즈 페이지 디자인 수정
  src/main/resources/static/common/js/common.js
  src/main/resources/static/css/common.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/static/css/sub.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/post.js
  src/main/resources/templates/views/post/add.html
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/post/update.html
  src/main/resources/templates/views/post/updatewriter.html
  src/main/resources/templates/views/post/writer.html
  src/main/resources/templates/views/series/add.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
  src/main/resources/templates/views/story/home.html
  src/main/resources/templates/views/story/posts.html
  src/main/resources/templates/views/story/series.html
Labels: ✨ Feature, 🎨Style

#173 #83, 172 수익 적립 내역, 정산 요청 내역
  src/main/java/com/pentoryall/common/page/Pagination.java
  src/main/java/com/pentoryall/settlement/controller/SettlementController.java
  src/main/java/com/pentoryall/settlement/dto/UserRevenueDTO.java
  src/main/java/com/pentoryall/settlement/mapper/SettlementMapper.java
  src/main/java/com/pentoryall/settlement/service/SettlementService.java
  src/main/resources/mappers/SettlementMapper.xml
  src/main/resources/templates/views/settlement/revenueList.html
  src/main/resources/templates/views/settlement/settlementList.html
Labels: ✨ Feature

#175 #83 정산 요청 기능
  src/main/java/com/pentoryall/point/service/TransactionService.java
  src/main/java/com/pentoryall/portone/controller/PortOneApiController.java
  src/main/java/com/pentoryall/portone/service/PortOneService.java
  src/main/java/com/pentoryall/settlement/controller/SettlementController.java
  src/main/java/com/pentoryall/settlement/dto/SettlementDTO.java
  src/main/java/com/pentoryall/settlement/mapper/SettlementMapper.java
  src/main/java/com/pentoryall/settlement/service/SettlementService.java
  src/main/resources/mappers/SettlementMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/static/css/point.css
  src/main/resources/static/css/sub.css
  src/main/resources/static/js/settlement.js
  src/main/resources/templates/views/settlement/settlement.html
  src/main/resources/templates/views/user/settlement/add.html
Labels: ✨ Feature

#176 #170 only author writer
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/dto/ReportPostDTO.java
  src/main/java/com/pentoryall/post/mapper/ReportPostMapper.java
  src/main/java/com/pentoryall/post/service/ReportPostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/resources/mappers/LikePostMapper.xml
  src/main/resources/mappers/ReportPostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/templates/views/post/list.html
  src/main/resources/templates/views/post/postComment.html
  src/main/resources/templates/views/post/postReport.html
  src/main/resources/templates/views/series/page.html
Labels: ✨ Feature

#178 #177 설정 페이지 사이드 메뉴의 탭 active 처리
  src/main/java/com/pentoryall/settlement/controller/SettlementController.java
  src/main/java/com/pentoryall/settlement/controller/UserSettlementController.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/resources/static/css/sub.css
  src/main/resources/templates/fragments/settings/sidebar.html
Labels: 🔧Refactor

#180 feature/#174 정산조회 장르추가 중복확인
  src/main/java/com/pentoryall/admin/controller/CommentReportController.java
  src/main/java/com/pentoryall/admin/controller/PayManageController.java
  src/main/java/com/pentoryall/admin/dtos/PayManageDTO.java
  src/main/java/com/pentoryall/admin/dtos/userSettlementDTO.java
  src/main/java/com/pentoryall/admin/mappers/CommentReportMapper.java
  src/main/java/com/pentoryall/admin/mappers/PayManageMapper.java
  src/main/java/com/pentoryall/admin/service/CommentReportService.java
  src/main/java/com/pentoryall/admin/service/PayManageService.java
  src/main/resources/application-yml
  src/main/resources/mappers/CommentReportMapper.xml
  src/main/resources/mappers/PayManageMapper.xml
  src/main/resources/templates/views/admin/adminCommentReport.html
  src/main/resources/templates/views/admin/adminGenre.html
  src/main/resources/templates/views/admin/adminSettlement.html
Labels: ✨ Feature

#181 #179 첫 번째 포스트로 이동 및 시리즈,포스트 crud에러 해결
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/java/com/pentoryall/series/controller/SeriesController.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/mappers/SeriesMapper.xml
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/update.html
Labels: 🐞Bug, ✨ Feature

#182 #70 회원기능 좋아요 기능
  src/main/java/com/pentoryall/email/controller/AccountController.java
  src/main/java/com/pentoryall/email/service/RegisterMail.java
  src/main/java/com/pentoryall/user/controller/UserController.java
  src/main/java/com/pentoryall/user/mapper/UserMapper.java
  src/main/java/com/pentoryall/user/service/UserService.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/static/js/email.js
  src/main/resources/templates/views/user/findPwd.html
  src/main/resources/templates/views/user/regist.html
Labels: ✨ Feature

#185 #183 작가 닉네임을 누르면 작가의 마이 스토리로 이동 및 인기 포스트 출력시 해당하는 시리즈 함께 나오도록 수정
  src/main/java/com/pentoryall/admin/controller/payManageController.java
  src/main/java/com/pentoryall/admin/service/payManageService.java
  src/main/java/com/pentoryall/common/controller/MainController.java
  src/main/java/com/pentoryall/post/dto/PostSeriesDTO.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/static/js/common.js
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/series/page.html
  src/main/resources/templates/views/series/select.html
Labels: 🔧Refactor

#186 파일명 버그 수정
  src/main/java/com/pentoryall/admin/controller/PayManageController.java
  src/main/java/com/pentoryall/admin/controller/payManageController.java
  src/main/java/com/pentoryall/admin/service/PayManageService.java
  src/main/java/com/pentoryall/admin/service/payManageService.java
Labels: 🐞Bug

#187 포스트 페이지 디자인을 변경
  src/main/java/com/pentoryall/post/controller/PostController.java
  src/main/java/com/pentoryall/post/mapper/PostMapper.java
  src/main/java/com/pentoryall/post/service/PostService.java
  src/main/resources/mappers/PostMapper.xml
  src/main/resources/static/css/post.css
  src/main/resources/templates/views/post/list.html
Labels: 🎨Style

#189 #188 관리자 페이지 링크 및 정산 요청 페이지의 null 처리
  src/main/resources/static/css/common.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/settlement/settlement.html
  src/main/resources/templates/views/story/home.html
Labels: 🔧Refactor

#190 Git 파일 오류 수정
  src/main/java/com/pentoryall/admin/controller/SettlementManageController.java
  src/main/java/com/pentoryall/admin/mappers/SettlementManageMapper.java
  src/main/java/com/pentoryall/admin/service/SettlementManageService.java
  src/main/resources/mappers/SettlementManageMapper.xml
Labels: 🐞Bug

#192 #191 관리자 페이지 html, css, js 일부 수정
  src/main/java/com/pentoryall/admin/controller/CommentReportController.java
  src/main/java/com/pentoryall/admin/controller/ModifyPostController.java
  src/main/java/com/pentoryall/admin/controller/PostReportController.java
  src/main/java/com/pentoryall/admin/controller/SettlementManageController.java
  src/main/resources/mappers/SettlementManageMapper.xml
  src/main/resources/static/css/admin.css
  src/main/resources/templates/views/admin/adminCommentReport.html
  src/main/resources/templates/views/admin/adminPostModify.html
  src/main/resources/templates/views/admin/adminPostReport.html
  src/main/resources/templates/views/admin/adminSettlement.html
  src/main/resources/templates/views/admin/adminUser.html
Labels: 🔧Refactor

#195 Favicon 추가
  src/main/resources/static/images/common/favicon.ico
  src/main/resources/static/images/common/favicon.jpg
  src/main/resources/templates/fragments/head.html
Labels: 🎨Style

#197 오타 수정
  src/main/resources/templates/views/post/update.html
  src/main/resources/templates/views/settlement/settlement.html
  src/main/resources/templates/views/user/likePage.html
Labels: 🐞Bug

#201 README 수정
  README.md
Labels: 📚 Docs

#203 #202 시리즈,포스트,댓글 테스트 케이스 구현
  src/main/java/com/pentoryall/comment/mapper/CommentMapper.java
  src/main/resources/mappers/CommentMapper.xml
  src/main/resources/templates/views/index.html
  src/test/java/com/pentoryall/post/mapper/PostMapperTests.java
  src/test/java/com/pentoryall/series/mapper/SeriesMapperTests.java
Labels: ✅Test
